# This is a basic workflow to help you get started with Actions

name: Buid and Test Perl

env: 
  WORKFLOW_VERSION: 1.0.0
  WORKFLOW_DESCRIPTION: A basic workflow to build and test perl HelloWorld.
  WORKFLOW_BOOKSTACK_URL:

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  perl:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Use the perl container in my account?
    container:
      image: ghcr.io/zushane/perl:20210408.0.0
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Display the current perl version
      - name: perl version
        run: perl -v
      
      # Display /etc/issue
      - name: /etc/issue
        run: cat /etc/issue
      
      # Display the environment
      - name: environment
        run: env
        
      # Build perl HelloWorld
      - name: Build perl HelloWorld
        run: |
          perl Build.PL
          ./Build manifest
          ./Build
      
      # Test HelloWorld
      - name: Test perl HelloWorld
        run: ./Build test
        
      # Pizza Party
      - name: Pizza Party
        run: echo "🍕 Ham & Pineapple, please!"

