name: Create New Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      #### PREP ENVIRONMENT ####
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Install standard-version
        run: npm install -g standard-version

      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      #### SETUP RELEASE ####
      # Store the changelog in a variable for later use. Web encodes it.
      - name: Get changelog
        id: get_changelog
        run: |
          changelog=`standard-version --git-tag-fallback --dry-run | sed -n '/^---$/,/^---$/p' | grep -v '^---$'`
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "$changelog"
          echo "::set-output name=changelog::$changelog"

      - name: Setup git ID
        run: |
          git config --global user.name 'zushane'
          git config --global user.email 'sd@zu.com'

      # Store tag for use in creating release.
      - name: Create release
        id: standard-version
        run:
          standard-version --git-tag-fallback -a
          echo ::set-output name=version-tag::$(git describe --tags $(git rev-list --tags --max-count=1))

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Push release changes
        run: |
          git push origin main

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          release_name: ${{ steps.package-version.outputs.current-version }}
          body: ${{ steps.get_changelog.outputs.changelog }}
          draft: false
          prerelease: false

